### ISSUE TITLE
How about adding a discussion section ?

### ISSUE THREAD

**Issue by statquant** [fastverse/fastverse#108]
Another suggestion (sorry)
What about adding a discussion section like [this for instance](https://github.com/quarto-dev/quarto-cli/discussions) ?

Typically, I was looking for the fastest way to orthogonalize a matrix on another in R and this would well (?) fit the purpose of this repo.

**Comment by SebKrantz** [comment]
Thanks. I have started a discussion. Please suggest any packages there. In general yes, fast matrix packages that cover range of common operations can be featured.
