### ISSUE TITLE
Error in fastverse_extend()

### ISSUE THREAD

**Issue by davidnov** [fastverse/fastverse#57]
Hi,

First off, thank you very much for the package -- I am a big fan of the overarching goal. I just wanted to flag an error that just cropped up. As far as I can tell, nothing changed on my end. Removing and reinstalling the package (either with `install.packages()` or from a tar ball with `R CMD INSTALL` didn't resolve the issue. It seems like it stems from the `rule()` call within `fastverse_attach()`, but I couldn't resolve the issue. Any help with this would be greatly appreciated.

Minimal example illustrating the issue (in a fresh R session) with the incremental output:

```
> library(fastverse)
-- Attaching packages --------- fastverse 0.2.4 --
v data.table  1.14.3          v collapse    1.8.7      
v magrittr    2.0.3.9000      v matrixStats 0.62.0.9000
v kit         0.0.12          v fst         0.9.8      
-- Conflicts ------------ fastverse_conflicts() --
x collapse::fdroplevels() masks data.table::fdroplevels()
> fastverse_extend("ggplot2")
Error in rep("-", w) : invalid 'times' argument
> 
```

Nothing above is unique to `ggplot2` -- same happens when it is a vector of packages, or when the package name is unquoted. And output of `sessionInfo()`:

```
> print(sessionInfo())
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] fst_0.9.8              
[2] matrixStats_0.62.0-9000
[3] collapse_1.8.7         
[4] kit_0.0.12             
[5] magrittr_2.0.3.9000    
[6] data.table_1.14.3      
[7] fastverse_0.2.4        

loaded via a namespace (and not attached):
[1] compiler_4.2.1 parallel_4.2.1 tools_4.2.1   
[4] Rcpp_1.0.9     fstcore_0.9.12
> 
```
**EDIT** This issue only seems to arise in RStudio -- the same error does not arise when running R in console. RStudio version information below:

```
RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
```

**Comment by davidnov** [comment]
Follow-up on a couple additional things attempted, one which successfully resolved the issue:

- Reinstalling RStudio Desktop IDE (**failed to resolve**)
- Running update.packages() which triggered all of the following updates: `c("callr", "cluster", "collapse", "datawizard", "forcats", "furrr", "gert", "haven", "hms", "pillar", "RcppArmadillo", "readxl", "rmarkdown", "rstudioapi", "rvest", "scales", "sf", "stringr", "tinytex", "viridisLite"))` (**resolved the issue**)

Unfortunately, I don't know _which_ of the package updates above ended up being critical. If I were a betting man, it'd be `rstudioapi` (newest version 0.14) but I didn't have the patience to go one-by-one. 

At any rate, I'll go ahead and close thing issue, but hopefully this will serve as a (partial) resource in case someone else runs into this.

**Comment by SebKrantz** [comment]
Thanks! Yeah it seems the variable `w` is masked by something else. Not able to reproduce the issue through.

**Comment by davidnov** [comment]
Not suggesting that this necessarily needs to be re-opened, but I have also run into this same issue running VSCode with an R extension + `radian`. Interestingly, a similar error to before (although a bit more informative) now hits immediately upon adding `fastverse`, as below:

```
R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
Platform: x86_64-apple-darwin17.0 (64-bit)

R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
Platform: x86_64-apple-darwin17.0 (64-bit)

r$> .vsc.attach()

r$> library(fastverse)
Error: package or namespace load failed for ‘fastverse’:
 .onAttach failed in attachNamespace() for 'fastverse', details:
  call: rep("-", w)
  error: invalid 'times' argument

r$>
```

As I understand it, the one thing in common between RStudio and the above VSCode approach is how they handle running code snippets/selections (called "bracketed paste" in VSCode's R extension). Any idea what would be masking `w`?

**Comment by davidnov** [comment]
Blah, re-install of `fastverse`  with re-compilation, i.e., `remotes::install_github("fastverse/fastverse")` seems to have resolved it, at least in VSCode.

**Comment by SebKrantz** [comment]
Thanks! I have renamed the argument to `width` now, perhaps it helps. The code is in the `rule()` function at the bottom of this script: https://github.com/fastverse/fastverse/blob/main/R/utils.R. In this function there is also a call to `.Options$width`, to get the width of the console, which may be a problem on some plattforms..
