### ISSUE TITLE
Remove magrittr dependency for base pipe

### ISSUE THREAD

**Issue by barryrowlingson** [fastverse/fastverse#61]
You could remove the dependency on magrittr and use the base pipe `|>` - it would require some fairly trivial rewriting of examples:

```
DT %>% gby(country) %>% gv(9:13) %>% fmean
```

needs some brackets for the `fmean`:

```
DT |> gby(country) |> gv(9:13) |> fmean()
```

I guess any examples that use piping to `dot` to send the pipe to non-first args will need changing to use underscore, for R version 4.2.0 and later...

Base pipe should be faster, but maybe you've already thought about this and decided to stay with magrittr?

**Comment by SebKrantz** [comment]
Thanks, but I tend to disagree. There are actually 4 pipes in magrittr and I use all of them, and there are useful functions such as extract() which I use to pipe data.table syntax (and a bunch of other useful functions like set_attr() etc). Removing it would also be a major breaking change for those who expect it to be there. Overall I find  magrittr provides a nice and comprehensive solution to the piping problem and I don’t see base R coming anywhere close to that.

**Comment by barryrowlingson** [comment]
Sure, I'll close this but at least its here if anyone else asks now! I'll stick with the bizarro pipe...
