### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by waynelapierre** [fastverse/fastverse#74]
I suggest that JuliaCall and alike should be removed. Based on my and many others' experience, Julia has failed to deliver the performance claimed by its enthusiasts. See two example posts:
https://discourse.julialang.org/t/with-missings-julia-is-slower-than-r/11838
https://discourse.julialang.org/t/my-experience-as-a-julia-and-r-user/83613

The misinformation and marketing of Julia have caused many R users, including myself, to lose valuable time. Think about this, if Julia is really that fast, why are there no major firms using it at all in the area of ML, CFD, or HPC?

Currently, more of Julia's issues have emerged. For example, see this post:
https://yuri.is/not-julia/

**Comment by SebKrantz** [comment]
Thanks for these insights and resources! I confess I have not used Julia yet, my view is that Julia is an emerging language that is faster to execute than R for numerical problems, but whose development is at an early stage. It was more of a spontaneous idea to add a section on R bindings to faster languages. The fact that I listed these connectors there is not a sign of my endorsement of Julia, I just wanted to be comprehensive. From the objective of the fastverse I am more critical of JuliaCall having 11 dependencies, which is even topped by rextendr with 29 dependencies. I expect any resonable person to use C and C++ to extend R, as far as I understand it is not even possible to have an R package with Julia backend as Julia is also a garbage collected language.
